### ISSUE TITLE
Recurrent error on PAR requests

### ISSUE THREAD

**Issue by Goncalves-Rafael** [OpenBanking-Brasil/applications-exemplo#11]
I just download the project and tried executing the payment flow with Mock Bank as in the presentation, but I'm not able to perform a succesfull PAR flow, the PAR endpoint just keeps returning the following error:

>   tpp:consent Create a PAR resource +1ms
OPError: invalid_request_object (Request Object claims are invalid)
    at processResponse (C:\Users\rafae\workspace\github\applications-exemplo\tpp-payments-client\node_modules\openid-client\lib\helpers\process_response.js:38:13)
    at FAPI1Client.pushedAuthorizationRequest (C:\Users\rafae\workspace\github\applications-exemplo\tpp-payments-client\node_modules\openid-client\lib\client.js:1575:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async generateRequest (C:\Users\rafae\workspace\github\applications-exemplo\tpp-payments-client\index.js:448:21)
    at async C:\Users\rafae\workspace\github\applications-exemplo\tpp-payments-client\index.js:805:61 {
  error: 'invalid_request_object',
  error_description: 'Request Object claims are invalid'
}
  tpp:consent Create a authorisation request url using PAR +741ms

So I tried executing through Postman, and if I just keep insisting in the request, then I get a successfull response sometimes. The request object sent is the following:
`eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZHQ00iLCJjdHkiOiJvYXV0aC1hdXRoei1yZXErand0Iiwia2lkIjoiMTYyMjYzMDQxMDAzNi01ZDJlYzk1NGZlIn0.KcvO8rZPm989ZQucC0eh-3Z1BZLWH7xTLDlB5pE7x0sTmGD7dViE7O1tcBTBejiJvhuksMLbAvA5DtK1LfUV4EocfVzF7-E1BAYeBLbu2cKyFE4_NhWNn1VL60lF6zncZZT7CR0JFPGn7DVpiGuLuUsQNZypT_2mO4eFUCkwLXcpMKrEa2qi00fKEGk-m1M6F3plX3vnkCnkPO7FM6m4VDKifrqC6eusWVanQuqoK-bKlDb8es5B0Dr0zdZhMRyX9KY8QeTlYhgvcVoIsQo_xk9E50j_eYQ5VxeT0wWfNGvYl88aUvtlNv_Fr6XC9LYUuSE3tKRlxKgpoaoofCkWiw.1N3q8OwuQYhizNwb.219ldG-wb8bVhbPO25TjYhUmfAjnCVfmoi01HJ95MVl4Ce206Ptj4Gz_-WexTFA1KUQYAPfAYo1iLZMUuyXPkImQ8G0-TfRjtZ2CzeHIgEzA-XwoInJPaNq_8D7LNkeiBxUjxdBP1YNCsEKfXVe1FN4eEXQ3weufO8fI6Dfa0Z8y6UZ1-P0fmoFf6XnQG6NB1UN0oKJeWdNeKXMR50GQWXy7wkO5heNuHkaloBbsHUxFSpFOKyxC6Po0VrkX-3XjWsR4LNwA1vy8WOwIzGxSIin7lZ23ECGFRQ_eX8sjrGhaxQA4afiVTi2hc7E2L5oij_SDfayXv_03WyRf1I4MXnSY3EWFgYuB_vjQ2h3XXg52kj9ZDTbOa64Blag53CAmgt8rI2dKiL_jZUcB2E4earaJsMVYV7sDJWhXKBkuk_JfFPdkG63ABSfts-nME2NSCaQBh3kKEjhurfceoRAyI2cxYiZimK1zRvOtCSY8Kn5TrkHhkfDGqWw20XulNA1xbFOPBDeHjUpKZTWBlTx7ZQac4QygpLGNzRWcv0QHOsTS6EvcL54sMJ8flK2ph5AOJe0Kqrc2EsljsVZl0qo4VPWB7ZQ7xHZTRMAG9NRwkxiw1b4aKYBTCAlzjn9S5S3-w2CJ9VwGZKFw_amvod6J0BtitoQ1LEYmhQShS2alIlzVw_4hIFqw1-JLOrVN9MZWxuOFE1at5rz8bqX285VVmqPpasyjvXukLoZEINFqGEvj7mzoVHidsVfoQfRVdeWTgTiOhXCxZbHJSi6CH8fyLbnfsizm88ZAzMOKXw-pSaWnpeSG15nrRmKKngH-girUrpnsXOtPKJnUG-K8ZYFBjNTMU94roF1hCFqufOf6MpNYXj6UOeSFGaqvkHpWQx-vaePMfRv3qgiKWdn0Vd4LeXGXUKAcv3m_q2DxidRZBVS0x1A_TTfLyHcWh_wtL-auwuRJV1sCTMvqNhtXLW7DJOyjyoMJs0Tb93UKGn2msGOqNHc9-vCZszNnbTdbi-I4Kyoo_znUbaDOcB5uAf1uO-cUKLEISNLtYv2PpN_4f20wbOC3FazZLqd5WVOtKWug_5i_alYNv7PsQll8rLzBLuMkk2FRSOVgxhIH_6fDF-JySLN_vDUu5ILwtAij9Xv1qZHRIQiWOpwaw5_eCD8iq2nmckJ8uSjQS1uEZSg0qz4kXX3YEMS6SOPzjkLSa_8XcZHqoz4333GG7n-hGnCAfkUciEYPpCkDMDO4kohc3BCdFsYZEU4StF5JIV2lVxL-hzo-A4yq9ecoDgsvP7xUKwLRpW4pqdVeqa5tzDD9hOkuLgKtZHaLNWdNz0iBYcETuRZ6qF1J3Gk-WAHF_RmawalNfeRxgXi_VKbqTldOxR0jqkB4wg0xehJCX2GP21DqFWRf-x-7y9DDCyzJzQDkDehR8i3EqC3fOs4PaQUNzT2Cx3CkxOqGy15SyXNEwKeOF0JFuvtf9OM8EgaQr3EMU20D0EAXcS4JSgNAlJuRKZlYxx7nxN-Tbs_2a5dWbFlf00K_OK1xEG0plfpV8frNLi2q9uilhrgC2yX83Nr-G9lyqikLDvZ4tFLEgeZvHSjxmeRUI2wegaSFNzGum1vfLkB5aHg-P24nZx5tvF-c9wrc7vW8aV-nW9_U8jAyhgPkHXgw00-GGvn33kUa_HDxEQdK2PmcDV_ehF18kMZJ0XJXSO1RBMDNDFraoa8qJToMN8nDFXLIswsjf-OPIUYp27QhLXypchev1jJ07OPGsVljqyT9u5YVZtAP8UJdGg-dBKzPhvgfUBAigyw5zRpco349-x6dFf-jYA8B8XJU-pxF2b46csv_5nMDZlZ_uiaZhjakRPi_e_3A7dnzBqgFGcffHymUmdMp1Ir1SyrEHVAgivh4BIrHPIZYhON-ivr8Xm78d2otLY-zqg18dAeIffGYFKHJtj2M5F-ju2XtgrnYELJOoADpXS0Cwejtazo.ya8G0wQyDoayV9TpEBXi3A`

Is this behaviour expected? I was not able to identify what is wrong with the generated claims in the project or if the error is with Mock Bank API.

**Comment by EkkeErick** [comment]
@RalphBragg

**Comment by EkkeErick** [comment]
Yes Please. 

Open the ticket on https://gitlab.com/obb1/certification/-/issues?sort=created_date&state=opened and we will get the Mock TPP and Mock Bank Engineers to take a look at it.

**Comment by Goncalves-Rafael** [comment]
Ok, thanks, I will do that!
